root: true
extends: "plugin:@mysticatea/es2020"

ignorePatterns:
  - dist/

parser: "@typescript-eslint/parser"

rules:
  no-void: "off"

settings:
  node:
    tryExtensions: 
      - .ts

overrides:
  - files: "./*.ts"
    excludedFiles: "./*-definition.ts"
    rules:
      no-shadow: "off"
  - files: "*-definition.ts"
    rules:
      "@mysticatea/ts/no-empty-interface": "off"
